import ctypes

# Window constants
user32 = ctypes.windll.user32
WINDOW_HEIGHT = user32.GetSystemMetrics(1) - 200
WINDOW_WIDTH = user32.GetSystemMetrics(0) - 100
WINDOW_X = 20
WINDOW_Y = 20

# Padding constants
OUTER_PADDING = 10
INNER_PADDING = 5

# Right frame constants
LEFT_FRAME_HEIGHT = WINDOW_HEIGHT - 2 * OUTER_PADDING
LEFT_FRAME_WIDTH = 0.20 * (WINDOW_WIDTH - 6 * OUTER_PADDING)

# Middle frame constants
MIDDLE_FRAME_HEIGHT = WINDOW_HEIGHT - 2 * OUTER_PADDING
MIDDLE_FRAME_WIDTH = 0.70 * (WINDOW_WIDTH - 6 * OUTER_PADDING)

# Right frame constants
RIGHT_FRAME_HEIGHT = WINDOW_HEIGHT - 2 * OUTER_PADDING
RIGHT_FRAME_WIDTH = 0.10 * (WINDOW_WIDTH - 6 * OUTER_PADDING)
